###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server1.iiitd.edu.in)
#  Generated on:      Tue Apr 15 20:59:36 2025
#  Design:            PROCESSOR
#  Command:           create_ccopt_clock_tree_spec -file /home/mrinank22305/Desktop/Processor/ccopt_new.spec -keep_all_sdc_clocks -views view1
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clock true

# Clocks present at pin clock
#   clock (period 7.100ns) in timing_config sdc1([/home/mrinank22305/Desktop/Processor/dft_report/dft_constraints_for_physical_design_min_area_dft_CORE65LPSVT_nom_1.05V_125C.sdc])
create_ccopt_clock_tree -name clock -source clock -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay1 -early -clock_tree clock 2.000

set_ccopt_property target_max_trans_sdc -delay_corner delay1 -late -clock_tree clock 2.000
# Clock period setting for source pin of clock
set_ccopt_property clock_period -pin clock 7.1

# Skew group to balance non generated clock:clock in timing_config:sdc1 (sdc /home/mrinank22305/Desktop/Processor/dft_report/dft_constraints_for_physical_design_min_area_dft_CORE65LPSVT_nom_1.05V_125C.sdc)
create_ccopt_skew_group -name clock/sdc1 -sources clock -auto_sinks
set_ccopt_property include_source_latency -skew_group clock/sdc1 true
set_ccopt_property extracted_from_clock_name -skew_group clock/sdc1 clock
set_ccopt_property extracted_from_constraint_mode_name -skew_group clock/sdc1 sdc1
set_ccopt_property extracted_from_delay_corners -skew_group clock/sdc1 delay1


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

