# ####################################################################

#  Created by Encounter(R) RTL Compiler v14.10-s022_1 on Wed Apr 09 01:30:23 +0530 2025

# ####################################################################

set sdc_version 1.7

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design PROCESSOR

create_clock -name "clock" -add -period 7.1 -waveform {0.0 3.55} [get_ports clock]
set_clock_transition 2.0 [get_clocks clock]
set_load -pin_load 1.0 [get_ports zero]
set_clock_gating_check -setup 0.0 
set_input_transition 2.0 [get_ports reset]
set_ideal_network [get_ports reset]
set_ideal_network [get_ports scan_en]
set_wire_load_mode "enclosed"
set_wire_load_selection_group "default_by_area" -library "CORE65LPHVT"
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_BK1SX1]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_BK1X1]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPHQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPRQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_DFPSQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPBTQX9]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQNTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQNTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQNTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPHRQTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPRQX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQNX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQTX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQTX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQTX35]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQX18]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQX27]
set_dont_use [get_lib_cells CORE65LPHVT/HS65_LH_SDFPSQX35]
set_clock_uncertainty -setup 2.0 [get_clocks clock]
