# ####################################################################

#  Created by Encounter(R) RTL Compiler v14.10-s022_1 on Wed Apr 09 13:25:32 +0530 2025

# ####################################################################

set sdc_version 1.7

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design PROCESSOR

create_clock -name "clock" -add -period 7.1 -waveform {0.0 3.55} [get_ports clock]
set_clock_transition 2.0 [get_clocks clock]
set_load -pin_load 1.0 [get_ports zero]
set_clock_gating_check -setup 0.0 
set_input_transition 2.0 [get_ports reset]
set_ideal_network [get_ports reset]
set_ideal_network [get_ports scan_en]
set_wire_load_mode "enclosed"
set_wire_load_selection_group "default_by_area" -library "CORE65LPSVT"
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_BK1SX1]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_BK1X1]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPHQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPRQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_DFPSQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPBTQX9]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQNTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQNTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQNTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPHRQTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPRQX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQNX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQTX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQTX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQTX35]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQX18]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQX27]
set_dont_use [get_lib_cells CORE65LPSVT/HS65_LS_SDFPSQX35]
set_clock_uncertainty -setup 2.0 [get_clocks clock]
